# Netlify configuration for Joakim Eskils Portfolio
# Next.js 15 with App Router - Static Export

[build]
  # Build command without Turbopack for Netlify compatibility
  command = "npm run build"
  
  # Publish directory for Next.js static export
  publish = "out"
  
  # Base directory (root of the project)
  base = "/"

# Environment variables for build
[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Next.js specific environment variables
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Build optimization
  NODE_OPTIONS = "--max-old-space-size=4096"
  
  # Ensure devDependencies are installed
  NODE_ENV = "development"

# Production context settings
[context.production]
  command = "npm run build"
  publish = "out"
  
  [context.production.environment]
    NODE_ENV = "development"

# Deploy preview context (for pull requests)
[context.deploy-preview]
  command = "npm run build"
  publish = "out"
  
  [context.deploy-preview.environment]
    NODE_ENV = "development"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"
  publish = "out"
  
  [context.branch-deploy.environment]
    NODE_ENV = "development"

# Development context for Netlify Dev
[context.dev.environment]
  NODE_ENV = "development"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions directory (if you add serverless functions later)
[functions]
  directory = "netlify/functions"

# Netlify Dev configuration
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
  targetPort = 3000

# Form handling (if you add forms later)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
